from typing import Optional
import numpy as np
import gymnasium as gym

import pygame

#
# Coverage Path Planning (CPP) environment — partial-observability compliant.
#
# Per the assignment requirement, the agent does NOT have access to a complete
# map of the environment. It must build its own understanding through
# exploration. Observations expose only:
#
#   - "agent": 7 floats — pose, coverage so far, and 4 directional unvisited
#     ratios. The directional ratios are computed over the *visited* set, so
#     they reflect what the agent has discovered, not the ground-truth grid.
#
#   - "neighbors": 5x5 matrix centred on the agent. This is the agent's local
#     "sensor view": it shows free / obstacle / visited cells in a small
#     neighborhood. Cells outside the grid are encoded as walls.
#         0 = free / unvisited (and inside the grid)
#         1 = obstacle or wall (out-of-bounds counts as wall)
#         2 = already visited
#
#   - "visited_map": (size, size) binary memory of cells the agent has
#     already visited. This is information *generated by the agent's own
#     trajectory*, analogous to the occupancy map a robot builds online via
#     SLAM. It does not leak ground truth about unexplored obstacles.
#
# Action masking (used by MaskablePPO) only masks moves that would leave the
# grid (the size of the grid is treated as known geometry, like the floor of
# a physical room). Obstacles are NOT masked: the agent must discover them
# through its 5x5 sensor view and the stuck penalty when it bumps into one.
#

class GridWorldCPPEnv(gym.Env):

    metadata = {"render_modes": ["human", "rgb_array"], "render_fps": 4}

    def __init__(self, render_mode=None, size: int = 5, obs_quantity: int = 3, max_steps: int = 200):
        self.size = size
        self.window_size = 512
        self.obs_quantity = obs_quantity
        self.obstacles_locations = []
        self.count_steps = 0
        self.max_steps = max_steps
        self.consecutive_revisits = 0

        self.visited = set()

        self._agent_location = np.array([-1, -1], dtype=int)
        self._neighbors = np.zeros((5, 5), dtype=int)

        # Cached structures (populated in reset()) — NOT exposed to the agent.
        self._obstacle_set: set = set()
        self._obstacle_grid: np.ndarray = np.zeros((size, size), dtype=bool)

        # Pre-built coordinate arrays for vectorised _get_directional_signals().
        _r = np.arange(size)
        self._xs, self._ys = np.meshgrid(_r, _r, indexing='ij')

        self.observation_space = gym.spaces.Dict({
            "agent": gym.spaces.Box(
                low=np.zeros(7, dtype=np.float32),
                high=np.ones(7, dtype=np.float32),
                dtype=np.float32,
            ),
            "neighbors": gym.spaces.Box(
                low=np.zeros((5, 5), dtype=np.float32),
                high=np.full((5, 5), 2.0, dtype=np.float32),
                dtype=np.float32,
            ),
            "visited_map": gym.spaces.Box(
                low=0.0,
                high=1.0,
                shape=(size, size),
                dtype=np.float32,
            ),
        })

        self.action_space = gym.spaces.Discrete(4)
        self._action_to_direction = {
            0: np.array([1, 0]),   # right
            1: np.array([0, -1]),  # up
            2: np.array([-1, 0]),  # left
            3: np.array([0, 1]),   # down
        }

        assert render_mode is None or render_mode in self.metadata["render_modes"]
        self.render_mode = render_mode

        self.window = None
        self.clock = None

    @property
    def total_free_cells(self):
        return self.size * self.size - len(self.obstacles_locations)

    @property
    def coverage_ratio(self):
        return len(self.visited) / self.total_free_cells if self.total_free_cells > 0 else 1.0

    def _visited_grid(self) -> np.ndarray:
        grid = np.zeros((self.size, self.size), dtype=bool)
        if self.visited:
            vis_arr = np.array(list(self.visited), dtype=int)
            grid[vis_arr[:, 0], vis_arr[:, 1]] = True
        return grid

    def _get_directional_signals(self, visited_grid: Optional[np.ndarray] = None):
        # Directional ratios are computed over visited_grid only. The
        # denominator uses size*size minus visited count, which is what the
        # agent can compute from its own memory — it does NOT use the
        # ground-truth obstacle layout.
        ax, ay = self._agent_location

        if visited_grid is None:
            visited_grid = self._visited_grid()
        # Treat anything not yet visited as "potentially unvisited free".
        unvisited_known = ~visited_grid

        right_mask = self._xs > ax
        up_mask    = self._ys < ay
        left_mask  = self._xs < ax
        down_mask  = self._ys > ay

        signals = np.zeros(4, dtype=np.float32)
        for idx, dir_mask in enumerate((right_mask, up_mask, left_mask, down_mask)):
            total = dir_mask.sum()
            if total > 0:
                signals[idx] = float((unvisited_known & dir_mask).sum()) / float(total)
        return signals

    def set_neighbors(self):
        # 5x5 sensor view around the agent. Out-of-bounds = wall (1).
        # Obstacles in this window become observable to the agent only when
        # the window covers them.
        ax, ay = self._agent_location

        pad = 2
        padded = np.ones((self.size + 2 * pad, self.size + 2 * pad), dtype=int)
        padded[pad:pad + self.size, pad:pad + self.size] = 0

        if self._obstacle_set:
            obs_arr = np.array(list(self._obstacle_set), dtype=int)
            padded[obs_arr[:, 0] + pad, obs_arr[:, 1] + pad] = 1

        if self.visited:
            vis_arr = np.array(list(self.visited), dtype=int)
            vx = vis_arr[:, 0] + pad
            vy = vis_arr[:, 1] + pad
            not_obs = padded[vx, vy] != 1
            padded[vx[not_obs], vy[not_obs]] = 2

        cx, cy = ax + pad, ay + pad
        self._neighbors = padded[cx - 2:cx + 3, cy - 2:cy + 3].T

    def _get_obs(self):
        visited_grid = self._visited_grid()
        dir_signals = self._get_directional_signals(visited_grid)
        return {
            "agent": np.array([
                self._agent_location[0] / max(self.size - 1, 1),
                self._agent_location[1] / max(self.size - 1, 1),
                self.coverage_ratio,
                dir_signals[0],
                dir_signals[1],
                dir_signals[2],
                dir_signals[3],
            ], dtype=np.float32),
            "neighbors": self._neighbors.astype(np.float32),
            "visited_map": visited_grid.astype(np.float32),
        }

    def _get_info(self):
        return {
            "coverage": self.coverage_ratio,
            "visited_cells": len(self.visited),
            "total_free_cells": self.total_free_cells,
            "steps": self.count_steps,
            "size": self.size,
        }

    def action_masks(self) -> np.ndarray:
        # Only mask moves that would step out of the grid. The grid bounds are
        # known geometry of the world; obstacles are NOT masked, since the
        # agent has not yet discovered them in general.
        ax, ay = self._agent_location
        mask = np.zeros(4, dtype=bool)
        for action, direction in self._action_to_direction.items():
            nx, ny = ax + direction[0], ay + direction[1]
            if 0 <= nx < self.size and 0 <= ny < self.size:
                mask[action] = True
        if not mask.any():
            mask[:] = True
        return mask

    def _rebuild_obstacle_caches(self):
        self._obstacle_set = set(tuple(loc) for loc in self.obstacles_locations)
        self._obstacle_grid = np.zeros((self.size, self.size), dtype=bool)
        if self._obstacle_set:
            obs_arr = np.array(list(self._obstacle_set), dtype=int)
            self._obstacle_grid[obs_arr[:, 0], obs_arr[:, 1]] = True

    def reset(self, seed: Optional[int] = None, options: Optional[dict] = None):
        super().reset(seed=seed)
        self.count_steps = 0
        self.obstacles_locations = []
        self.visited = set()
        self.consecutive_revisits = 0

        self._agent_location = self.np_random.integers(0, self.size, size=2, dtype=int)

        _tmp_obs_set: set = {tuple(self._agent_location)}
        for _ in range(self.obs_quantity):
            obstacle_location = self._agent_location.copy()
            while tuple(obstacle_location) in _tmp_obs_set:
                obstacle_location = self.np_random.integers(0, self.size, size=2, dtype=int)
            self.obstacles_locations.append(obstacle_location)
            _tmp_obs_set.add(tuple(obstacle_location))

        self._rebuild_obstacle_caches()
        self.visited.add(tuple(self._agent_location))
        self.set_neighbors()

        observation = self._get_obs()
        info = self._get_info()

        if self.render_mode == "human":
            self._render_frame()

        return observation, info

    def step(self, action):
        direction = self._action_to_direction[action]
        old_location = self._agent_location.copy()

        self._agent_location = np.clip(
            self._agent_location + direction, 0, self.size - 1
        )

        if tuple(self._agent_location) in self._obstacle_set:
            self._agent_location = old_location

        self.set_neighbors()
        self.count_steps += 1

        current_pos = tuple(self._agent_location)
        is_new_cell = current_pos not in self.visited
        stayed_in_place = np.array_equal(self._agent_location, old_location)

        # Reward shaping (v3.1):
        #  - Step base penalty -0.05.
        #  - Stuck penalty -0.5 BACK because the agent must discover obstacles
        #    by bumping into them (action masking only blocks out-of-bounds).
        #  - New cell +1.0; revisit -0.25.
        #  - Full coverage bonus +10*(size/5).
        #  - No truncation penalty (keeps value bootstrap unbiased).
        reward = -0.05
        if stayed_in_place:
            reward -= 0.5
            self.consecutive_revisits += 1
        elif is_new_cell:
            reward += 1.0
            self.visited.add(current_pos)
            self.consecutive_revisits = 0
        else:
            reward -= 0.25
            self.consecutive_revisits += 1

        full_coverage = len(self.visited) >= self.total_free_cells
        terminated = full_coverage
        truncated = self.count_steps >= self.max_steps and not terminated

        if full_coverage:
            reward += 10.0 * (self.size / 5.0)

        observation = self._get_obs()
        info = self._get_info()

        if self.render_mode == "human":
            self._render_frame()

        return observation, reward, terminated, truncated, info

    def render(self):
        if self.render_mode == "rgb_array":
            return self._render_frame()

    def _render_frame(self):
        if self.window is None and self.render_mode == "human":
            pygame.init()
            pygame.display.init()
            self.window = pygame.display.set_mode(
                (self.window_size, self.window_size)
            )
        if self.clock is None and self.render_mode == "human":
            self.clock = pygame.time.Clock()

        canvas = pygame.Surface((self.window_size, self.window_size))
        canvas.fill((255, 255, 255))
        pix_square_size = self.window_size / self.size

        for cell in self.visited:
            cell_arr = np.array(cell)
            pygame.draw.rect(
                canvas,
                (144, 238, 144),
                pygame.Rect(
                    pix_square_size * cell_arr,
                    (pix_square_size, pix_square_size),
                ),
            )

        for obs in self.obstacles_locations:
            pygame.draw.rect(
                canvas,
                (0, 0, 0),
                pygame.Rect(
                    pix_square_size * obs,
                    (pix_square_size, pix_square_size),
                ),
            )

        pygame.draw.circle(
            canvas,
            (0, 0, 255),
            (self._agent_location + 0.5) * pix_square_size,
            pix_square_size / 3,
        )

        font = pygame.font.SysFont(None, 24)
        coverage_text = font.render(
            f"Coverage: {self.coverage_ratio:.1%} | Steps: {self.count_steps}",
            True, (0, 0, 0)
        )
        canvas.blit(coverage_text, (5, 5))

        for x in range(self.size + 1):
            pygame.draw.line(canvas, 0, (0, pix_square_size * x),
                             (self.window_size, pix_square_size * x), width=3)
            pygame.draw.line(canvas, 0, (pix_square_size * x, 0),
                             (pix_square_size * x, self.window_size), width=3)

        if self.render_mode == "human":
            self.window.blit(canvas, canvas.get_rect())
            pygame.event.pump()
            pygame.display.update()
            self.clock.tick(self.metadata["render_fps"])
        else:
            return np.transpose(
                np.array(pygame.surfarray.pixels3d(canvas)), axes=(1, 0, 2)
            )

    def close(self):
        if self.window is not None:
            pygame.display.quit()
            pygame.quit()
